title: "Deep learning with TensorFlow"
author: "Development Seed"
email: "lilly@developmentseed.org"
release: "1"
logo: 'ds.png'

# Short description about the book
description: >-
  Notebook tutorials demonstrating advanced techniques for use of deep learning with TensorFlow and earth observation data.

execute:
#  execute_notebooks           : auto
  execute_notebooks           : off
  timeout: -1

# HTML-specific settings
html:
  favicon              : "ds.png"
  home_page_in_navbar  : false
  use_edit_page_button : true
  use_repository_button: true
  use_issues_button    : true
  extra_footer: |
     <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
     <a property="dct:title" rel="cc:attributionURL" 
      href="https://developmentseed.org/tensorflow-eo-training-2/">Deep Learning with TensorFlow and EO Data</a> was funded by <a property="dct:title" rel="cc:attributionURL"
      href="https://www.nasa.gov/servir/">NASA SERVIR</a> and is licensed under <a href="https://www.apache.org/licenses/LICENSE-2.0" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Apache License, Version 2.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://www.apache.org/foundation/press/kit/asf_logo.svg"></a>
     </p> 

# Interact link settings
notebook_interface            : "notebook"

repository:
  url           : "https://github.com/developmentseed/tensorflow-eo-training-2/"
  branch        : main
  path_to_book  : ds_book

# Launch button settings
#launch_buttons:
#  binder             : false
#  binderhub          : false
#  binderhub_url      : off
#  jupyterhub         : false
#  thebe              : false
#  colab              : false

# Launch button settings
launch_buttons:
#  notebook_interface: classic #jupyterlab
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com


# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
   
latex:
  latex_engine                : "pdflatex"
  use_jupyterbook_latex       : true # use jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: ds_book.tex
    
sphinx:
  config:
    html_show_copyright: false
    latex_toplevel_sectioning: 'section'
#    latex_show_urls: 'footnote'
    latex_elements.papersize: a4paper
    latex_elements.pointsize: 12pt
    

#google_analytics:
#  mytrackingcode: UA-205698170-1
